version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "review"
      - "dependencies"
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
      - "review"
      - "dependencies"
